### PR TITLE
Resolve #123: list_systems returns a list

### LINKED ISSUE #123: list_systems doesn't return an iterable
Is there a good reason for the following discrepancy?
```
catalog = SystemCatalog()
# works just fine
for category in list_categories(catalog)
    println(category)
end
category1 = first(list_categories(catalog))
# error: list_systems doesn't return an iterable.
for system_name in list_systems(catalog, category1)
    println(system_name)
end
```
Also: `list_systems` behaves identically to `show_systems`, when `list_categories` and `show_categories` are meaningfully different. That seems like a recipe for confusion.

### PR DESCRIPTION
**Pull request by luke-kiernan**
Make `list_systems` return a list: now `list_systems(catalogue, category)` returns the (sorted) names of the systems in `category`, or in the default catalog if `catalog` is omitted.

### CODE REVIEW

File: src/system_catalog.jl [hunk 1]
```diff
@@ -32,6 +32,21 @@ end
...
 
+function list_systems(category::Type{<:SystemCategory})
+    catalog = SystemCatalog()
+    return list_systems(catalog, category)
+end
+
+function list_systems(catalog::SystemCatalog, category::Type{<:SystemCategory})
+    data = catalog.data
+    if haskey(data, category)
+        return sort(collect(keys(data[category])); by = x -> string(x))
```
Comment (daniel-thom) [inline src/system_catalog.jl:43]: Nit: probably better to sort in place.
```suggestion
        return sort!(collect(keys(data[category])); by = x -> string(x))
```

**Review by daniel-thom — APPROVED** [review]
I only looked the changes related to list_systems.
